// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/task_handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/api/task_handler.go -destination=internal/api/task_handler_mock_test.go -package api
//

// Package api is a generated GoMock package.
package api

import (
	context "context"
	reflect "reflect"
	domain "todo/internal/entities/domain"
	dto "todo/internal/entities/dto"
	task "todo/internal/usecase/task"

	gomock "go.uber.org/mock/gomock"
)

// MockDtoValidator is a mock of DtoValidator interface.
type MockDtoValidator struct {
	ctrl     *gomock.Controller
	recorder *MockDtoValidatorMockRecorder
	isgomock struct{}
}

// MockDtoValidatorMockRecorder is the mock recorder for MockDtoValidator.
type MockDtoValidatorMockRecorder struct {
	mock *MockDtoValidator
}

// NewMockDtoValidator creates a new mock instance.
func NewMockDtoValidator(ctrl *gomock.Controller) *MockDtoValidator {
	mock := &MockDtoValidator{ctrl: ctrl}
	mock.recorder = &MockDtoValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDtoValidator) EXPECT() *MockDtoValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockDtoValidator) Validate(arg0 dto.DTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockDtoValidatorMockRecorder) Validate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockDtoValidator)(nil).Validate), arg0)
}

// MockTaskService is a mock of TaskService interface.
type MockTaskService struct {
	ctrl     *gomock.Controller
	recorder *MockTaskServiceMockRecorder
	isgomock struct{}
}

// MockTaskServiceMockRecorder is the mock recorder for MockTaskService.
type MockTaskServiceMockRecorder struct {
	mock *MockTaskService
}

// NewMockTaskService creates a new mock instance.
func NewMockTaskService(ctrl *gomock.Controller) *MockTaskService {
	mock := &MockTaskService{ctrl: ctrl}
	mock.recorder = &MockTaskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskService) EXPECT() *MockTaskServiceMockRecorder {
	return m.recorder
}

// AddTagByID mocks base method.
func (m *MockTaskService) AddTagByID(ctx context.Context, addTagCmd task.TagCommand) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTagByID", ctx, addTagCmd)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTagByID indicates an expected call of AddTagByID.
func (mr *MockTaskServiceMockRecorder) AddTagByID(ctx, addTagCmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTagByID", reflect.TypeOf((*MockTaskService)(nil).AddTagByID), ctx, addTagCmd)
}

// Create mocks base method.
func (m *MockTaskService) Create(ctx context.Context, createCmd task.CreateCommand) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, createCmd)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTaskServiceMockRecorder) Create(ctx, createCmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaskService)(nil).Create), ctx, createCmd)
}

// DeleteTagByID mocks base method.
func (m *MockTaskService) DeleteTagByID(ctx context.Context, deleteTagCmd task.TagCommand) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTagByID", ctx, deleteTagCmd)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTagByID indicates an expected call of DeleteTagByID.
func (mr *MockTaskServiceMockRecorder) DeleteTagByID(ctx, deleteTagCmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTagByID", reflect.TypeOf((*MockTaskService)(nil).DeleteTagByID), ctx, deleteTagCmd)
}

// DeleteTaskByID mocks base method.
func (m *MockTaskService) DeleteTaskByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTaskByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTaskByID indicates an expected call of DeleteTaskByID.
func (mr *MockTaskServiceMockRecorder) DeleteTaskByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTaskByID", reflect.TypeOf((*MockTaskService)(nil).DeleteTaskByID), ctx, id)
}

// QueryTasks mocks base method.
func (m *MockTaskService) QueryTasks(ctx context.Context, queryCmd task.QueryCommand) ([]domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryTasks", ctx, queryCmd)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryTasks indicates an expected call of QueryTasks.
func (mr *MockTaskServiceMockRecorder) QueryTasks(ctx, queryCmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryTasks", reflect.TypeOf((*MockTaskService)(nil).QueryTasks), ctx, queryCmd)
}

// ReadByID mocks base method.
func (m *MockTaskService) ReadByID(ctx context.Context, id int64) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadByID", ctx, id)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadByID indicates an expected call of ReadByID.
func (mr *MockTaskServiceMockRecorder) ReadByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadByID", reflect.TypeOf((*MockTaskService)(nil).ReadByID), ctx, id)
}

// UpdateByID mocks base method.
func (m *MockTaskService) UpdateByID(ctx context.Context, updateCmd task.UpdateCommand) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, updateCmd)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockTaskServiceMockRecorder) UpdateByID(ctx, updateCmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockTaskService)(nil).UpdateByID), ctx, updateCmd)
}
