// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/task/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/task/repository.go -destination=internal/usecase/task/repository_mock_test.go -package task
//

// Package task is a generated GoMock package.
package task

import (
	context "context"
	reflect "reflect"
	domain "todo/internal/entities/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddTagByID mocks base method.
func (m *MockRepository) AddTagByID(ctx context.Context, addCmd TagCommand) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTagByID", ctx, addCmd)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTagByID indicates an expected call of AddTagByID.
func (mr *MockRepositoryMockRecorder) AddTagByID(ctx, addCmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTagByID", reflect.TypeOf((*MockRepository)(nil).AddTagByID), ctx, addCmd)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, task domain.Task) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, task)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, task)
}

// DeleteByID mocks base method.
func (m *MockRepository) DeleteByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockRepository)(nil).DeleteByID), ctx, id)
}

// DeleteTagByID mocks base method.
func (m *MockRepository) DeleteTagByID(ctx context.Context, deleteCmd TagCommand) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTagByID", ctx, deleteCmd)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTagByID indicates an expected call of DeleteTagByID.
func (mr *MockRepositoryMockRecorder) DeleteTagByID(ctx, deleteCmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTagByID", reflect.TypeOf((*MockRepository)(nil).DeleteTagByID), ctx, deleteCmd)
}

// QueryTasks mocks base method.
func (m *MockRepository) QueryTasks(ctx context.Context, cmd QueryCommand) ([]domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryTasks", ctx, cmd)
	ret0, _ := ret[0].([]domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryTasks indicates an expected call of QueryTasks.
func (mr *MockRepositoryMockRecorder) QueryTasks(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryTasks", reflect.TypeOf((*MockRepository)(nil).QueryTasks), ctx, cmd)
}

// ReadByID mocks base method.
func (m *MockRepository) ReadByID(ctx context.Context, id int64) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadByID", ctx, id)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadByID indicates an expected call of ReadByID.
func (mr *MockRepositoryMockRecorder) ReadByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadByID", reflect.TypeOf((*MockRepository)(nil).ReadByID), ctx, id)
}

// UpdateByID mocks base method.
func (m *MockRepository) UpdateByID(ctx context.Context, updateCmd UpdateCommand) (domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, updateCmd)
	ret0, _ := ret[0].(domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockRepositoryMockRecorder) UpdateByID(ctx, updateCmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockRepository)(nil).UpdateByID), ctx, updateCmd)
}
