package middleware

import (
	"net/http"
	"net/http/httptest"
	"testing"
	"todo/internal/utils/ctxutils"
)

func TestLog_RequestID_Auto(t *testing.T) {
	var gotRequestID string

	mw := &Log{}
	next := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotRequestID = ctxutils.RequestID(r.Context())
		w.WriteHeader(http.StatusOK)
	})
	req := httptest.NewRequest(http.MethodGet, "/", nil)
	rec := httptest.NewRecorder()
	mw.RequestID(next).ServeHTTP(rec, req)

	if gotRequestID == "" {
		t.Fatal("expected autogenerated requestID with `xid.New().String()`")
	}
	if rec.Code != http.StatusOK {
		t.Fatalf("expected 200 response code, got %d", rec.Code)
	}
}

func TestLog_RequestID_Header(t *testing.T) {
	var gotRequestID string
	testRequestID := "test-request-id"

	mw := &Log{}
	next := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotRequestID = ctxutils.RequestID(r.Context())
		w.WriteHeader(http.StatusOK)
	})
	req := httptest.NewRequest(http.MethodGet, "/", nil)
	req.Header.Set(requestIDHeader, testRequestID)
	rec := httptest.NewRecorder()
	mw.RequestID(next).ServeHTTP(rec, req)

	if gotRequestID != testRequestID {
		t.Fatalf("expected requestID %s, got %s", testRequestID, gotRequestID)
	}
	if rec.Code != http.StatusOK {
		t.Fatalf("expected 200 response code, got %d", rec.Code)
	}
}
